README.md
Minor edits to improve readability and corrected small typos.
=> MAINT: minor edits in README

openg2p_disbursement/models/openg2p_disbursement_batch.py
Fixed the disbursement notifications to show the fails and success notification for job batch users.
=> [FIX] Issue #39 : Disbursement Notifications

openg2p/models/openg2p_beneficiary.py, openg2p/views/openg2p_beneficiary.xml, openg2p_registration/models/openg2p_registration.py, openg2p_registration/models/openg2p_submission_registration_map.py, openg2p_registration/views/openg2p_registration.xml
- UI fixes in registration and beneficiary
- grand total (LE) instead of grand total (USD)
- default country changed to "Sierra Leone"
- default state changed to "Freetown (SL)"
- default city changed to "Freetown"
- registration/beneficiary name = name of school
=> [FIX] UI fixes

openg2p_registration/models/__init__.py, openg2p_registration/models/openg2p_registration.py, openg2p_registration/models/openg2p_registration_api.py
- odk data filter
- registration API
- get all registrations
- get registration by id
- create new registration
=> registration API

openg2p/models/beneficiary_to_batch_wizard.py, openg2p_disbursement_advice/models/openg2p_disbursement_batch_transaction.py, openg2p_disbursement_advice/views/openg2p_disbursement_batch_transaction.xml
- Added total,completed,ongoing,failed amount
- Correction in datetime format
- ui changes
=> Summary API

odk-connector/models/odk_config_model.py, openg2p_disbursement_advice/models/env-format.txt
- added decorator causing issues
- env file format
=> api model decorator added

odk-connector/models/odk_submissions_model.py, openg2p_disbursement_advice/__manifest__.py, openg2p_registration/models/openg2p_registration.py
- Added exception handling while creating registrations
- Error aggregation of failed cases of registration
@avikganguly01 @SubhamPramanik Please review this.
=> Exception handling and handling ODK pull error

odk-connector/models/odk_submissions_model.py, openg2p_registration/models/openg2p_registration.py
- Added try-catch block for odk submissions model 
- Termination function calls after exception
Link to the stack trace of the error faced : [https://pastebin.com/MK2GPrST](https://pastebin.com/MK2GPrST)
@avikganguly01 @SubhamPramanik please review this .
=> [FIX] Added exception handling and null checker

odk-connector/models/odk_submissions_model.py
=> [FIX] odk None checker fix

openg2p_disbursement_advice/__manifest__.py
=> Disbursement Bug Resolve

odk-connector/models/odk_submissions_model.py, openg2p/models/openg2p_beneficiary.py, openg2p/views/openg2p_beneficiary.xml, openg2p_registration/models/openg2p_demographic_authentication.py, openg2p_registration/models/openg2p_registration.py
- Added marital field and gender field
- Included loggers and merging of programs
=> Added marital,loggers,gender and merging of programs

openg2p/views/openg2p_beneficiary.xml, openg2p_disbursement/views/action_menu.xml, openg2p_registration/views/openg2p_registration.xml
- Added pagination to all three models i.e. registration, beneficiary, and disbursement.
- Please review and let me know. @avikganguly01 and @truthfool
=> added pagination 

openg2p/models/openg2p_beneficiary.py, openg2p_registration/data/openg2p_registration_data.xml, openg2p_registration/models/openg2p_registration.py, openg2p_registration/views/openg2p_registration.xml
- moved verification stage before deduplication stage
@avikganguly01 @truthfool
=> stage change for verification and deduplication

odk-connector/models/odk.py, odk-connector/models/odk_config_model.py, odk-connector/models/odk_submissions_model.py, odk-connector/views/action.xml, openg2p_registration/models/registration_service.py
- changes in the XML definition
- datetime for submissions is taking as current  datetime without timezone 
- added loggers and removed print statements
- formatted with black
=> Changes for odk-connector for odoo v14

openg2p_program/__manifest__.py, openg2p_program/models/openg2p_beneficiary.py, openg2p_program/models/openg2p_program.py, openg2p_program/models/openg2p_program_enrollment.py, openg2p_program/models/openg2p_program_enrollment_category.py, openg2p_program/security/security.xml, openg2p_program/views/openg2p_program.xml, openg2p_program/views/openg2p_program_enrollment.xml, openg2p_program/views/openg2p_program_enrollment_category.xml, openg2p_program/wizard/enroll_beneficiary.py, openg2p_program/wizard/enroll_beneficiary.xml
- changes in the XML definition
- changes in decorators in models
- removed demo data loading 
- formatted with black
=> changes in module program for odoo v14

requirements.txt
- Updated the requirements which was causing docker image build failure in odoo 14
@avikganguly01 @SubhamPramanik @fynmanoj
=> new requirements for odoo 14

Dockerfile
- added python package setuptools wheel to resolve build issue
@avikganguly01 @SubhamPramanik @fynmanoj
=> changes in docker file

openg2p/data/openg2p_demo.xml, openg2p/models/res_country_state.py, openg2p_registration/__manifest__.py
- Loading demo data into registration and beneficiary module
@avikganguly01 @SubhamPramanik @fynmanoj
=> Demo data loaded

odk-connector/models/odk_submissions_service.py, openg2p/views/openg2p_beneficiary.xml, openg2p_registration/views/openg2p_registration.xml
- created tab view in registration model and beneficiary model
- black formatting
@avikganguly01 @truthfool
=> Tab view in registration and beneficiary model

odk-connector/models/odk_submissions_service.py
- function call correction
@avikganguly01  @truthfool
=> correcting function name

openg2p/models/openg2p_beneficiary_api.py, openg2p_disbursement/models/openg2p_disbursement_batch_transaction.py, openg2p_disbursement/models/res_partner_bank.py, openg2p_registration/models/openg2p_registration_api.py, openg2p_registration/models/registration_service.py
- Changes in batch transfer API
- Changes in batch summary API
- Changed default payment mode to slcb
- Added loggers removing print statements
@avikganguly01 @fynmanoj
=> Correction in batch transfer url

openg2p/__manifest__.py
- Removed storage s3 backend module as it is deprecated
@avikganguly01
=> Removed deprecated module
